site_name: MyTestProject Documentation

nav:
  - Home: index.md
  - Config: config.md

plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

theme:
  name: readthedocs