site_name: MyTestProject Documentation

use_directory_urls: false
plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

theme:
  name: material