site_name: MyTestProject Documentation


plugins:
  - search
  - mkdocstrings:
      include_package: extensions/opentelemetry


theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

